"""Stage 6: Assembly & Export agent.

Collects all deliverables, normalizes filenames, creates a manifest/README,
and bundles everything into a delivery ZIP package.
"""

from __future__ import annotations

import json
import zipfile
from datetime import datetime
from pathlib import Path

from .base import BaseAgent


class AssemblerAgent(BaseAgent):
    name = "AssemblerAgent"

    OUTPUT_PATH = "output"

    def run(self, spec: dict, dry_run: bool = False) -> Path:
        output_dir = self.project_dir / self.OUTPUT_PATH
        output_dir.mkdir(parents=True, exist_ok=True)

        if dry_run:
            readme = output_dir / "README.md"
            self.write_file(readme, self._stub_readme(spec))
            return output_dir

        deliverables = self._collect_deliverables(spec)
        manifest = self._build_manifest(deliverables, spec)

        readme_path = output_dir / "README.md"
        self.write_file(readme_path, manifest)

        # Create ZIP archive if there are multiple deliverables
        if len(deliverables) > 1:
            zip_path = self._create_zip(output_dir, deliverables, spec)
        else:
            zip_path = None

        # Write a JSON manifest for programmatic consumption
        json_manifest = {
            "generated": datetime.utcnow().isoformat() + "Z",
            "product_type": spec.get("product_type", "unknown"),
            "topic": spec.get("topic_angle", "unknown"),
            "files": [
                {
                    "filename": p.name,
                    "size_bytes": p.stat().st_size,
                    "path": str(p.relative_to(self.project_dir)),
                }
                for p in deliverables
                if p.exists()
            ],
        }
        manifest_json_path = output_dir / "manifest.json"
        manifest_json_path.write_text(json.dumps(json_manifest, indent=2), encoding="utf-8")

        return output_dir

    def revise(
        self,
        feedback: str,
        output_path: Path,
        spec: dict,
        dry_run: bool = False,
    ) -> Path:
        # Assembly revisions are scripted; re-run the assembly
        return self.run(spec, dry_run=dry_run)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _collect_deliverables(self, spec: dict) -> list[Path]:
        """Find all output files that should be included in the final package."""
        output_dir = self.project_dir / "output"
        candidates = []

        # Formatted primary deliverable
        for ext in (".pdf", ".docx", ".md", ".pptx", ".xlsx"):
            for p in output_dir.glob(f"*{ext}"):
                if p.name != "README.md" and p.stat().st_size > 0:
                    candidates.append(p)

        # Supplementary deliverables from assets
        assets_dir = self.project_dir / "assets"
        for p in assets_dir.rglob("*"):
            if p.is_file() and p.stat().st_size > 0:
                candidates.append(p)

        return candidates

    def _build_manifest(self, deliverables: list[Path], spec: dict) -> str:
        product_type = spec.get("product_type", "Digital Product")
        topic = spec.get("topic_angle", "")

        lines = [
            f"# Package Contents",
            f"",
            f"**Product:** {topic}",
            f"**Type:** {product_type}",
            f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d')}",
            f"",
            f"## Files",
            f"",
        ]

        for p in deliverables:
            size_kb = p.stat().st_size // 1024 if p.exists() else 0
            lines.append(f"- `{p.name}` ({size_kb} KB)")

        lines += [
            "",
            "## Usage",
            "",
            "Open the primary PDF file to read the main content.",
            "Supplementary files (worksheets, templates) are labeled accordingly.",
            "",
            "---",
            "*Generated by Content Factory*",
        ]
        return "\n".join(lines)

    def _create_zip(
        self, output_dir: Path, deliverables: list[Path], spec: dict
    ) -> Path:
        topic_slug = (
            spec.get("topic_angle", "product")
            .lower()
            .replace(" ", "-")[:40]
        )
        zip_path = output_dir / f"{topic_slug}-package.zip"
        readme_path = output_dir / "README.md"

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            if readme_path.exists():
                zf.write(readme_path, readme_path.name)
            for p in deliverables:
                if p.exists() and p != zip_path:
                    zf.write(p, p.name)

        return zip_path

    def _stub_readme(self, spec: dict) -> str:
        return (
            f"# Package Contents (dry-run stub)\n\n"
            f"**Product type:** {spec.get('product_type', 'unknown')}\n\n"
            "Files would be listed here after a full pipeline run.\n"
        )
